/**
 * AI Element Selector — Vite Dev Plugin
 * 
 * This plugin injects the AI Element Selector script into the HTML 
 * during development ONLY. It never modifies your source files.
 * 
 * This file is auto-generated by the AI Element Selector extension.
 * You can safely add it to .gitignore.
 */
export default function aiElementSelectorPlugin() {
  return {
    name: 'ai-element-selector',
    apply: 'serve', // Only active during `vite dev`, never in production builds
    transformIndexHtml(html) {
      return html.replace(
        '</body>',
        `    <!-- AI Element Selector (Dev Only) -->\n    <script src="http://localhost:3210/inject.js" async><\/script>\n  </body>`
      );
    }
  };
}
